wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1666609377
    t:
      1:
        - 1
        - 4
        - 5
        - 41
        - 53
        - 55
      2:
        - 1
        - 4
        - 5
        - 41
        - 53
        - 55
      3:
        - 16
      4: 3.8.13
      5: 0.12.21
      8:
        - 5
batch_size:
  desc: null
  value: 256
batch_size_test:
  desc: null
  value: 4
batch_size_val:
  desc: null
  value: 4
conv_dropout:
  desc: null
  value: 0
data_aug:
  desc: null
  value: false
dataset_dir:
  desc: null
  value: /MLAIM/AIMLab/Sheina/databases/VTdb/DL
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 20
fc_dropout:
  desc: null
  value: 0
gpu:
  desc: null
  value: '0'
loss:
  desc: null
  value: wCE
lr:
  desc: null
  value: 0.0001
model:
  desc: null
  value: TCN
models_dir:
  desc: null
  value: /MLAIM/AIMLab/Sheina/databases/VTdb/DL/models
optimizer:
  desc: null
  value: Adam
repo_root:
  desc: null
  value: /home/sheina/tsai/utiles
run_name:
  desc: null
  value: ''
seed:
  desc: null
  value: 0
train:
  desc: null
  value: true
use_sampler:
  desc: null
  value: true
weight:
  desc: null
  value: 36
win_len:
  desc: null
  value: 1
workers:
  desc: null
  value: 0
